### PR TITLE
* Added cleanup.sh

### PR DESCRIPTION
**Pull request by aleksei-burlakov**
- The cleanup.sh does recursively:
    1) Replace tabs with 4 spaces.
    2) Remove trailing spaces.

TODO:
    1) If the number of spaces is not multiple 4, make it be.
       E.g. 3 spaces --> 4 spaces. 7 spaces --> 8. 2 --> ?

### CODE REVIEW

**Comment by aleksei-burlakov** [comment]
@crazyss , @wjn740 please have a look at the formatter. It's simple for now. We can add then some more intelligence later.

**Comment by wjn740** [comment]
@coolgw

**Comment by coolgw** [comment]
Should we define the code style first?

**Comment by aleksei-burlakov** [comment]
We agreed on the linux kernel style on the last hackweek.

**Comment by wjn740** [comment]
hi @aleksei-burlakov , would you please put this tool into tool/ directory, create it.
And we could enhance it in the future. make it more richer.

**Comment by aleksei-burlakov** [comment]
> hi @aleksei-burlakov , would you please put this tool into tool/ directory, create it.
> And we could enhance it in the future. make it more richer.

Done!

**Pull request merged**
